baseurl = "https://rrra.org"
languageCode = "en-us"
title = "Red River Radio Amateurs"

theme = "twentyfourteen"
Paginate = 10
newcontenteditor = "vim"
enableEmoji = true
preserveTaxonomyNames = true

description = "News from the Red River Radio Amateurs"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
	email = "webmaster@rrra.org"
	name = "K0STK"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  dates = "dates"
  ncs = "ncs"
  authors = "authors"

[outputs]
	page = [ "HTML" ]
	home = [ "HTML", "RSS" ]
	section = [ "HTML", "RSS" ]
	taxonomy = [ "HTML", "Calendar", "RSS" ]
	taxonomyTerm = [ "HTML", "Calendar", "RSS" ]

[permalinks]
	post = "/post/:year/:month/:day/:slug/"
	calendar = "/cal/:year/:month/:day/:slug/"

[params]
  tel = "701-526-4426"         # Club Phone Number
  sitedate = "January 2, 2006" # Sitewide Date Format

	description = "A nonprofit ARRL affiliated Amateur Radio club serving Fargo, ND; Moorhead, MN; and the surrounding area with communication support and educational outreach."

	# Used for SK pages
	silentkeybase = "http://silentkeyhq.com/main.php?p=bin/NSKALookup.php&dlnk=&"

[params.categories]

[params.categories.education]
	description = "Content (e.g. blog posts, information pages, and files/links) about the activities of the RRRA Education Committee and educational topics of general interest."

[params.categories.hamfest]
	description = "Content (e.g. blog posts, information pages, and files/links) about RRRA Hamfests and the activities of the RRRA Hamfest Committee."

[params.categories.license-testing]
	description = "Content (e.g. blog posts, information pages, and files/links) about the activities of the RRRA Volunteer Examiner (VE) Committee and topics related to FCC license testing. Please visit the [License Testing Dates](/dates/license-testing/) page for information about what to bring to a testing session and how to find out when your license is granted."

[params.categories.membership]
  description = "Content (e.g. blog posts, information pages, and files/links) about membership in the RRRA. Please visit the [social dates page](/dates/social/), or check the *Upcoming Events* section of our [home page](/) for upcoming events." 

[params.categories.minutes]
	description = "Minutes recorded by the RRRA Secretary during the club's monthly business meetings. The minutes posted here are converted from the original source documents to Markdown; the source documents are archived on the [RRRA file sharing server](http://cloud.rrra.org) in the *Secretary's Reports* folder."

[params.categories.outreach]
	description = "Content (e.g. blog posts, information pages, and files/links) about RRRA activities intended to promote or advocate for Amateur Radio to the public, our government, and our served agencies."

[params.categories.public-service]
  description = 'Content (e.g. blog posts, information pages, and files/links) about the activities of the RRRA ARES Committee and the "voluntary noncommercial communication service, particularly with respect to providing emergency communications" (*["Amateur Radio Service." 47 "CFR" 97.1(a). 2016.](http://www.ecfr.gov/cgi-bin/text-idx?c=ecfr&rgn=div5&view=text&node=47:5.0.1.1.6&idno=47#se47.5.97_11)*), provided to the public by Amateur Radio operators.' 

[params.categories.technical]
  description = "Content (e.g. blog posts, information pages, and files/links) about the activities of the RRRA Technical Committee and the equipment/systems they maintain, along with technical topics of general interest."

[params.tooltips]

[params.tooltips.about]
  title="Information about RRRA and how to contact the club"

[params.tooltips.licensing]
  title="Get started in Amateur Radio with RRRA"

[params.tooltips.calendar]
  title="Club and regional events"

[params.tooltips.links]
  title="File downloads"

[params.tooltips.nets]
  title="Net Schedule, Preamble, and NCS Roster"

[params.tooltips.radios]
  title="Repeaters and SuperLINK"

[params.tooltips.sk]
  title="Memorials of RRRA Members who are Silent Keys"
